//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Demo_DatabaseFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CinemaDBEntities : DbContext
    {
        public CinemaDBEntities()
            : base("name=CinemaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChuDe> ChuDes { get; set; }
        public virtual DbSet<Phim> Phims { get; set; }
    
        public virtual int SP_CapNhatPhim(Nullable<int> id, string tieuDe, string moTa, string noiDung, string imageName, string tacGia, Nullable<int> chuDe)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var imageNameParameter = imageName != null ?
                new ObjectParameter("ImageName", imageName) :
                new ObjectParameter("ImageName", typeof(string));
    
            var tacGiaParameter = tacGia != null ?
                new ObjectParameter("TacGia", tacGia) :
                new ObjectParameter("TacGia", typeof(string));
    
            var chuDeParameter = chuDe.HasValue ?
                new ObjectParameter("ChuDe", chuDe) :
                new ObjectParameter("ChuDe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CapNhatPhim", idParameter, tieuDeParameter, moTaParameter, noiDungParameter, imageNameParameter, tacGiaParameter, chuDeParameter);
        }
    
        public virtual ObjectResult<SP_LayTatCaThongTinPhim_Result> SP_LayTatCaThongTinPhim()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LayTatCaThongTinPhim_Result>("SP_LayTatCaThongTinPhim");
        }
    
        public virtual ObjectResult<SP_LayThongTinChiTietPhim_Result> SP_LayThongTinChiTietPhim(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SP_LayThongTinChiTietPhim_Result>("SP_LayThongTinChiTietPhim", idParameter);
        }
    
        public virtual int SP_ThemMoiPhim(string tieuDe, string moTa, string noiDung, string imageName, string tacGia, Nullable<int> chuDe)
        {
            var tieuDeParameter = tieuDe != null ?
                new ObjectParameter("TieuDe", tieuDe) :
                new ObjectParameter("TieuDe", typeof(string));
    
            var moTaParameter = moTa != null ?
                new ObjectParameter("MoTa", moTa) :
                new ObjectParameter("MoTa", typeof(string));
    
            var noiDungParameter = noiDung != null ?
                new ObjectParameter("NoiDung", noiDung) :
                new ObjectParameter("NoiDung", typeof(string));
    
            var imageNameParameter = imageName != null ?
                new ObjectParameter("ImageName", imageName) :
                new ObjectParameter("ImageName", typeof(string));
    
            var tacGiaParameter = tacGia != null ?
                new ObjectParameter("TacGia", tacGia) :
                new ObjectParameter("TacGia", typeof(string));
    
            var chuDeParameter = chuDe.HasValue ?
                new ObjectParameter("ChuDe", chuDe) :
                new ObjectParameter("ChuDe", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ThemMoiPhim", tieuDeParameter, moTaParameter, noiDungParameter, imageNameParameter, tacGiaParameter, chuDeParameter);
        }
    
        public virtual int SP_XoaThongTinPhim(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("Id", id) :
                new ObjectParameter("Id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XoaThongTinPhim", idParameter);
        }
    }
}
